const URL='https://rlfxnjbqxbozjdzkbwlz.supabase.co';
const KEY='sb_publishable_rmVOQ3Orx49KpW_4uMqYew_c2HpcA87';
const sb=globalThis.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
let snapshot={assignments:[]},pendingFactorId='',pendingChallengeId='';
const trackNames={web:'Web Development','data-science':'AI / Data Science',cybersecurity:'Cybersecurity','3d-programming':'3D + Programming',robotics:'Robotics'};
const decisionNames={proposed:'Propuesta',confirmed:'Confirmado',revise:'Revisar',rejected:'Descartado'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function gateway(operation,args={}){const {data,error}=await sb.functions.invoke('teacher-auth-gateway',{body:{operation,args}});if(error)throw new Error(error.message||'gateway_error');if(data?.error)throw new Error(data.error);return data?.data}
async function beginMfa(){const {data:aal,error}=await sb.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;if(aal?.currentLevel==='aal2'){$('mfaPanel').classList.add('hidden');await load();return}const {data:factors,error:fError}=await sb.auth.mfa.listFactors();if(fError)throw fError;let factor=(factors?.totp||[]).find(x=>x.status==='verified');if(!factor){const {data:enrolled,error:e}=await sb.auth.mfa.enroll({factorType:'totp',friendlyName:'Seminar Project Board'});if(e)throw e;factor=enrolled;$('mfaQr').src=enrolled.totp.qr_code;$('mfaQr').classList.remove('hidden');$('mfaHelp').textContent='Scan the QR and enter the six-digit code.'}else{$('mfaQr').classList.add('hidden');$('mfaHelp').textContent='Enter the six-digit code from your authenticator.'}pendingFactorId=factor.id;const {data:challenge,error:cError}=await sb.auth.mfa.challenge({factorId:pendingFactorId});if(cError)throw cError;pendingChallengeId=challenge.id;$('mfaPanel').classList.remove('hidden')}
function filtered(){const g=$('groupFilter').value,t=$('trackFilter').value,q=$('searchInput').value.trim().toLowerCase();return (snapshot.assignments||[]).filter(a=>(!g||a.group_code===g)&&(!t||a.track_slug===t)&&(!q||((a.student_name+' '+a.project_title+' '+a.project_summary).toLowerCase().includes(q))))}
function renderMetrics(){const rows=snapshot.assignments||[];const proposed=rows.filter(x=>x.decision_status==='proposed').length;const confirmed=rows.filter(x=>x.decision_status==='confirmed').length;const revise=rows.filter(x=>x.decision_status==='revise').length;const tracks=new Set(rows.map(x=>x.track_slug)).size;$('metrics').innerHTML=[['Proyectos',rows.length],['Por definir hoy',proposed],['Confirmados',confirmed],['Por ajustar',revise],['Tracks',tracks]].map(([k,v])=>'<div class="metric"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('')}
function decisionActions(a){const id=esc(a.student_registry_id);return '<div class="decision-actions">'+(a.decision_status!=='confirmed'?'<button class="decision-confirm" data-id="'+id+'" data-decision="confirmed">Confirmar proyecto</button>':'<button class="secondary" data-id="'+id+'" data-decision="proposed">Reabrir propuesta</button>')+'<button class="secondary" data-id="'+id+'" data-decision="revise">Marcar para ajustar</button></div>'}
function card(a){const sprints=(a.sprints||[]).map(s=>'<article class="mini-sprint"><div class="step-no">S'+esc(s.n)+'</div><div><strong>'+esc(s.title)+'</strong><p>'+esc(s.goal)+'</p><small><b>Evidencia:</b> '+esc(s.deliverable)+'</small></div></article>').join('');return '<section class="panel proposal-card" data-group="'+esc(a.group_code)+'"><div class="proposal-head"><div><div class="project-meta"><span class="tag">'+esc(a.group_code)+'</span><span class="tag">'+esc(trackNames[a.track_slug]||a.track_slug)+'</span><span class="decision-badge" data-state="'+esc(a.decision_status||'proposed')+'">'+esc(decisionNames[a.decision_status]||a.decision_status||'Propuesta')+'</span></div><h2>'+esc(a.student_name)+'</h2><h3>'+esc(a.project_title)+'</h3><p class="lead">'+esc(a.project_summary)+'</p></div><div class="assignment-stack">'+(a.stack||[]).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div><div class="charter-grid"><div class="charter-card"><strong>Objetivo</strong><p>'+esc(a.objective)+'</p></div><div class="charter-card"><strong>Base de selección</strong><p>'+esc(a.source_ref||a.source_kind)+'</p></div></div>'+(a.safety_scope?'<div class="notice">'+esc(a.safety_scope)+'</div>':'')+(a.decision_note?'<div class="decision-note">'+esc(a.decision_note)+'</div>':'')+decisionActions(a)+'<details class="sprint-details"><summary>Ver desarrollo completo · 8 sprints</summary><div class="mini-sprints">'+sprints+'</div></details></section>'}
async function decide(id,status){const a=(snapshot.assignments||[]).find(x=>x.student_registry_id===id);if(!a)return;let note=a.decision_note||'';if(status==='revise'){const entered=window.prompt('¿Qué debe ajustarse en la propuesta de '+a.student_name+'?',note);if(entered===null)return;note=entered.trim()}if(status==='confirmed'&&!window.confirm('Confirmar como proyecto específico de '+a.student_name+'?'))return;try{await gateway('seminar_project_decision',{p_student_registry_id:id,p_decision_status:status,p_decision_note:note});await load()}catch(err){window.alert('No se pudo guardar la decisión: '+err.message)}}
function render(){renderMetrics();$('projectBoard').innerHTML=filtered().map(card).join('')||'<section class="panel">No hay proyectos para este filtro.</section>';document.querySelectorAll('[data-decision]').forEach(b=>b.addEventListener('click',()=>decide(b.dataset.id,b.dataset.decision)))}
async function load(){snapshot=await gateway('seminar_studio_dashboard');$('loginPanel').classList.add('hidden');$('boardPanel').classList.remove('hidden');$('updatedAt').textContent='Actualizado: '+new Date(snapshot.generated_at||Date.now()).toLocaleString('es-CO');render()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('teacherEmail').value.trim().toLowerCase();if(!email.endsWith('@ijr.edu.co')){$('loginStatus').textContent='Use the institutional @ijr.edu.co teacher account.';return}try{const {error}=await sb.auth.signInWithPassword({email,password:$('teacherPassword').value});if(error)throw error;$('teacherPassword').value='';await beginMfa()}catch(err){$('loginStatus').textContent=err.message}});
$('mfaButton').addEventListener('click',async()=>{const code=$('mfaCode').value.trim();if(!/^[0-9]{6}$/.test(code))return;try{const {error}=await sb.auth.mfa.verify({factorId:pendingFactorId,challengeId:pendingChallengeId,code});if(error)throw error;$('mfaCode').value='';await beginMfa()}catch(e){$('loginStatus').textContent=e.message}});
['groupFilter','trackFilter'].forEach(id=>$(id).addEventListener('change',render));$('searchInput').addEventListener('input',render);$('refreshButton').addEventListener('click',load);$('logoutButton').addEventListener('click',async()=>{await sb.auth.signOut({scope:'local'});$('boardPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden')});
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session)try{await beginMfa()}catch(e){$('loginStatus').textContent=e.message}})();