window.IJR_OOP_UML_DATA=Object.freeze({
  title:'OOP + UML Common Core',
  topics:[
    {slug:'object-model',n:1,title:'Class · Object · Instance',lead:'Separate the blueprint from the concrete object and identify responsibility before syntax.',modules:['m08'],uml:{name:'Robot',attrs:['- name: String','- battery: int'],ops:['+ move(): void','+ recharge(): void']},concepts:['A class defines structure and behavior.','An object is a concrete instance with identity and state.','Two instances can share the same class while holding different state.'],mistakes:['Calling every variable an object without checking its type.','Drawing UML after coding without reflecting the real implementation.'],evidence:['One class with a clear responsibility','Two different instances','A UML class box matching the code']},
    {slug:'state-behavior',n:2,title:'State & Behavior',lead:'Decide what an object knows and what an object does.',modules:['m08'],uml:{name:'BankAccount',attrs:['- owner: String','- balance: float'],ops:['+ deposit(amount): void','+ withdraw(amount): bool']},concepts:['State is stored in attributes/fields.','Behavior is expressed through methods.','Methods should protect meaningful object rules.'],mistakes:['Putting unrelated data inside one class.','Using methods that do not operate on the object responsibility.'],evidence:['State trace before/after a method','UML attributes and operations','Explanation of why each member belongs to the class']},
    {slug:'constructors',n:3,title:'Constructors & Valid State',lead:'Create objects that begin life in a coherent state.',modules:['m09'],uml:{name:'Student',attrs:['- name: String','- grade: int'],ops:['+ Student(name, grade)','+ promote(): void']},concepts:['Constructors initialize required state.','Parameters communicate what an object needs to exist.','Initialization rules prevent invalid objects.'],mistakes:['Creating empty objects and patching state later.','Duplicating initialization logic across the program.'],evidence:['Three valid objects','Constructor parameters justified','UML initialization represented consistently']},
    {slug:'encapsulation',n:4,title:'Encapsulation & Visibility',lead:'Protect state behind a controlled interface.',modules:['m10'],uml:{name:'Thermostat',attrs:['- temperature: float'],ops:['+ setTemperature(value): void','+ getTemperature(): float']},concepts:['Encapsulation separates internal representation from public use.','Visibility communicates intended access.','Validation belongs close to the state it protects.'],mistakes:['Making every field public.','Using getters/setters mechanically without an invariant.'],evidence:['Private/protected state','A rule enforced by a method','UML visibility symbols + / - / #']},
    {slug:'relationships',n:5,title:'Object Relationships',lead:'Model collaboration with association, aggregation and composition.',modules:['m12'],uml:{name:'Order',attrs:['- customer: Customer','- items: List<Item>'],ops:['+ total(): float','+ addItem(item): void']},concepts:['Association means objects know or use each other.','Aggregation models a weak whole-part relationship.','Composition models lifecycle ownership.'],mistakes:['Using inheritance where a has-a relationship is clearer.','Drawing composition without lifecycle ownership.'],evidence:['Three collaborating classes','Relationship type justified','One complete relationship represented in UML']},
    {slug:'inheritance',n:6,title:'Inheritance & Generalization',lead:'Use inheritance only when a real is-a relationship exists.',modules:['m11'],uml:{name:'Vehicle',attrs:['# speed: float'],ops:['+ move(): void','+ stop(): void']},concepts:['A subclass specializes a more general type.','Inherited behavior should represent a real common contract.','Generalization is shown with a hollow triangle toward the parent.'],mistakes:['Creating deep hierarchies for code reuse only.','Forcing unrelated classes into one parent.'],evidence:['Parent and child classes','One overridden behavior','Generalization arrow justified']},
    {slug:'polymorphism',n:7,title:'Polymorphism & Abstraction',lead:'Program against a common contract while allowing different implementations.',modules:['m11','m12'],uml:{name:'Shape',attrs:[],ops:['+ area(): float','+ draw(): void']},concepts:['Polymorphism lets one interface represent many concrete types.','Abstraction exposes essential behavior and hides irrelevant detail.','Interfaces or abstract classes make contracts explicit.'],mistakes:['Confusing overloading with overriding.','Adding abstraction without multiple meaningful implementations.'],evidence:['Common contract','At least two implementations','Same call producing type-specific behavior']},
    {slug:'architecture',n:8,title:'UML Class Diagram Architecture',lead:'Move from isolated classes to a complete model of responsibilities and relationships.',modules:['m14'],uml:{name:'ProjectSystem',attrs:['- services: List<Service>'],ops:['+ start(): void','+ status(): Report']},concepts:['A class diagram captures static structure.','Good architecture keeps responsibilities cohesive.','Packages/modules organize collaborating classes.'],mistakes:['Drawing every implementation detail.','Using one giant class for the whole system.'],evidence:['Diagram V2 with 3–6 classes','Responsibilities distributed coherently','Relationships labeled when useful']},
    {slug:'refactor-sync',n:9,title:'Refactoring · UML ↔ Code',lead:'Keep the model synchronized while the implementation changes.',modules:['m13','m14'],uml:{name:'Service',attrs:['- repository: Repository'],ops:['+ execute(): Result']},concepts:['Refactoring changes structure without changing intended behavior.','UML should evolve with the source code.','Tests make safe structural change possible.'],mistakes:['Updating code but leaving the diagram obsolete.','Changing architecture without a testable reason.'],evidence:['Before/after commit','Updated UML','Explanation of one structural improvement']},
    {slug:'defense',n:10,title:'Architecture Defense',lead:'Explain and modify the design live instead of only presenting a finished artifact.',modules:['m15'],uml:{name:'FinalProject',attrs:['- domainState: ...'],ops:['+ useCase(): ...']},concepts:['Architecture is a set of justified design decisions.','A diagram is useful only if it matches the running system.','Live modification demonstrates transferable understanding.'],mistakes:['Reading the diagram without explaining decisions.','Using patterns or inheritance because they look advanced.'],evidence:['Final synchronized class diagram','Live explanation of responsibilities','One small live change propagated to UML and code']}
  ]
});
